api_platform:
    title: Winker API
    version: 1.0.0
    formats:
#        jsonld: ['application/ld+json']
        json: [ 'application/json' ]
        html: [ 'text/html' ]
    patch_formats:
#        multipart: [ 'multipart/form-data' ]
        json: [ 'application/json' ]
#        jsonapi: [ 'application/vnd.api+json' ]
    error_formats:
        jsonproblem: [ 'application/problem+json' ]
        jsonld: [ 'application/ld+json' ]
        jsonapi: [ 'application/vnd.api+json' ]
    docs_formats:
        jsonld: ['application/ld+json']
        jsonopenapi: ['application/vnd.openapi+json']
        html: ['text/html']
    defaults:
        pagination_items_per_page: 10
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
        extra_properties:
            standard_put: true
            rfc_7807_compliant_errors: true
    event_listeners_backward_compatibility_layer: false
    keep_legacy_inflector: false
    collection:
        pagination:
            page_parameter_name: _page
    swagger:
        api_keys:
            JWT:
                name: Authorization
                type: header
