framework:
    messenger:
        # Uncomment this (and the failed transport below) to send failed messages to this transport for later handling.
        # failure_transport: failed
        transports:
#            user_notification_{userId}:
#                dsn: 'rdkafka://kafka:9093/user_notification_{userId}'
#                options:
#                    kafka_config:
#                        - { key: 'bootstrap.servers', value: 'kafka:9093' }
#                        - { key: 'group.id', value: 'symfony_user_notification_{userId}' }
#                        - { key: 'auto.offset.reset', value: 'earliest' }
        
        routing:
#            App\Message\UserTaskNotification: user_notification_{userId}
#        transports:
#            kafka:
#                dsn: 'enqueue://default'
#                options:
#                    topic: 'user_notifications'
                
#                dsn: '%env(KAFKA_DSN)%'
#                options:
#                    topic: 'user_notifications'
            
#            kafka:
#                dsn: '%env(KAFKA_DSN)%'
#                options:
#                    topic: 'user_notifications_*' # Wildcard для всіх користувачів
#                    queue: 'user_notifications'
            # https://symfony.com/doc/current/messenger.html#transport-configuration
            # async: '%env(MESSENGER_TRANSPORT_DSN)%'
            # failed: 'doctrine://default?queue_name=failed'
            # sync: 'sync://'
#            user_notifications:
#                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
#                options:
#                    exchange:
#                        name: 'user_notifications_exchange'
#                        type: direct
#                    queues: {}
#
#        routing:
#            App\Message\UserTaskNotification: kafka
#            # Route your messages to the transports
#            # 'App\Message\YourMessage': async
#            App\Message\NotificationInterface: user_notifications

# when@test:
#    framework:
#        messenger:
#            transports:
#                # replace with your transport name here (e.g., my_transport: 'in-memory://')
#                # For more Messenger testing tools, see https://github.com/zenstruck/messenger-test
#                async: 'in-memory://'
